export const apartment = [
  {
    status: 'sale',
    images: ['', ''],
    coverImage: '',
    availability: new Date('2025-06-01'),
    price: 400,
    district: 'Downtown',
    adress: 'Olmazor Tumani',
    room: 3,
    floor: 4,
    floorBuild: 9,
    square: 85,
    variant: '2',
    description: 'Просторная 3-комнатная квартира в центре города с видом на парк.',
    userId: 1,
  },
  {
    status: 'rent',
    images: ['', ''],
    coverImage: '',
    availability: new Date('2025-06-01'),
    price: 400,
    district: 'Downtown',
    adress: 'Yunusobod Tumani',
    room: 3,
    floor: 4,
    floorBuild: 9,
    square: 85,
    variant: 1,
    description: 'Просторная 3-комнатная квартира в центре города с видом на парк.',
    userId: 2,
  },
  {
    status: 'rent',
    images: ['', ''],
    coverImage: '',
    availability: new Date('2025-06-01'),
    price: 400,
    district: 'Downtown',
    adress: 'Chilonzor Tumani',
    room: 3,
    floor: 4,
    floorBuild: 9,
    square: 85,
    variant: 2,
    description: 'Просторная 3-комнатная квартира в центре города с видом на парк.',
    userId: 3,
  },
];

export const owner = [
  {
    fullName: 'Yusupov Doniyor',
    phone: '+9989978994512',
    userId: 1,
  },
  {
    fullName: 'Doniyor',
    phone: '+9989978994512',
    userId: 2,
  },
  {
    fullName: 'Yusupov',
    phone: '+9989978994512',
    userId: 3,
  },
];
